### ISSUE TITLE
Cannot add checkboxes to notes

### ISSUE THREAD

**Issue by jburns20** [HWComputerScience/iHW-Android#11]
As of v1.2, the gear icon that is supposed to appear next to notes when you're editing them does not appear, so it is no longer possible to add checkboxes to notes or mark them as important.

**Comment by ethanmad** [comment]
What version of Android is this on? Works on my devices. I'll test this further.

**Comment by jburns20** [comment]
Doesn't appear for me on nexus 5, Android 5.1

**Comment by ethanmad** [comment]
This gear, right? The gear only shows up when the edit text is selected.

**Comment by jburns20** [comment]
Never mind -- that's weird, it's working for me now.
