### ISSUE TITLE
Weekday pager bar is gone

### ISSUE THREAD

**Issue by jburns20** [HWComputerScience/iHW-Android#17]
There used to be a bar just below the action bar that showed the weekdays (Mon, Tue, etc.) It's not there anymore. See screenshots on Google play for what it used to look like.

**Comment by ethanmad** [comment]
You're right. Something felt like it was missing. I'll try to get it back
in there today.

**Comment by ethanmad** [comment]
cf49c125 is the first commit with issues (thanks `git bisect`!). Changes in lines 18 & 19 (updating the support libraries support-v4 and appcompat-v7 from 22.1.0 to 23.0.0) are causing the problem.

API 23 is finalized, so the fix might come in API 24.

The options I see:

1. Leave it as is (not my favorite option; seeing the day name is useful).
2. Attempt to fix with API 23 ("best" option, but might be futile or wasted effort with API 24).
3. Revert the commit and go back to API 22 (guaranteed to work).

Just to be clear, the bar we're discussing is [pts](https://github.com/HWComputerScience/iHW-Android/blob/v1.2/app/src/main/java/com/ihwapp/android/ScheduleActivity.java#L57) in ScheduleActivity? That's the only thing I see using the `dark_tan` drawable. Nothing there seems wrong (deprecated methods are in use for older API version, but that's not related). Anywhere else to look?

**Comment by ethanmad** [comment]
Applied option 3 in ea9e472. It's a stopgap and that's all. We should figure out how to move to API 23 soon.
