### ISSUE TITLE
Redownload schedule crashes

### ISSUE THREAD

**Issue by ile123ile** [HWComputerScience/iHW-Android#19]

**Comment by ethanmad** [comment]
Confirmed. Not able

**Comment by ile123ile** [comment]
Is it ok to just comment out setupactionbar? it doesn't appear to have one, always returns null

**Comment by ile123ile** [comment]
works completely fine without that it seems

**Comment by ethanmad** [comment]
I'll check it out when I get home. Can you commit your working changes to a
new branch on your fork? I'll pull from you.

**Comment by ile123ile** [comment]
When actually downloading the activities it never seems to download them, is that because the schedules aren't released?

**Comment by ile123ile** [comment]
Sorry forgot to put it in new branch, I'll do that now

**Comment by ethanmad** [comment]
Fixed in c38313f.
