### ISSUE TITLE
Course names are not unique and cause issues in editcourses

### ISSUE THREAD

**Issue by ile123ile** [HWComputerScience/iHW-Android#22]
More specifically it doesn't know which course to open

**Comment by ile123ile** [comment]
I'm getting this with my lunch (1st semester and 2nd) in my downloaded schedule, so this will be a common problem

**Comment by ile123ile** [comment]
Should I fix by adding an id to courses or by verifying the term as well

**Comment by ethanmad** [comment]
Either fix sounds OK. Share your solution with the iOS team because they
will need to implement it, too.

**Comment by ile123ile** [comment]
How do i share it with them?

**Comment by ile123ile** [comment]
Also I added it to my pull request

**Comment by ethanmad** [comment]
Fixed in ee1aa13.

**Comment by ethanmad** [comment]
Is this issue in the Play Store version (should be [v1.1.4](https://github.com/HWComputerScience/iHW-Android/releases/tag/1.1.4))? I'll backport this change if it is.
