### ISSUE TITLE
New icon (again)

### ISSUE THREAD

**Issue by ethanmad** [HWComputerScience/iHW-Android#24]
Srini Kumar, the same guy that made the previous icon, wanted to redo the iHW icon now that his skills have improved.

He told me, "I think it should be touched up. My skills weren't good back then," and (after seeing the old icon), "Woah shit that icon looks terrible. I can't believe I made that 😲."

![New icon](https://lh5.googleusercontent.com/-WHr7Ho0SoOE/Vfim7wMIqrI/AAAAAAAAQ4U/CpCGQcrmLcc/w844-h634-no/School.png)

Notice there are no stripes or folds in the new icon: "we want to avoid stripes and folds because the logo is already way too complicated."

To me, this icon conveys the same idea of the book/planner (the bookmark helps) and does so with less visual clutter. The spine of the book is a little bit nicer than in the previous icon and the colors are much prettier (they aren't exactly those defined in [`colors.xml`](https://github.com/HWComputerScience/iHW-Android/blob/master/app/src/main/res/values/colors.xml), so we may want to consider recoloring the app and/or the icon). The lack of Z-axis and drop shadow on the wolverine makes sense and more closely resembles the a physical book, while again reducing visual clutter.

Overall, I really like the icon and think it will look much better and "pop" more on screens.

Please discuss and share thoughts. I will forward them to Srini.

**Comment by jononon** [comment]
Love it, and its congruent with google material design.

**Comment by ile123ile** [comment]
Looks great, the old icon was a little too cluttered.

**Comment by jburns20** [comment]
Just a little nitpick -- in the above image, the loop of the tail is filled in with white. It should probably be changed to red.

**Comment by ethanmad** [comment]
@jburns20 sent that to Srini. His response: "I don't think it's a good idea. I've tried both ways. Showing details like that looks bad to me.

I'll do it, but I recommend against it."

It's ultimately your choice, so just let me know if you want him to redo the icon without the white fill-in.

**Comment by ile123ile** [comment]
Yeah looks good
